### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Donsome** [DQLin/VolumetricReSTIRRelease#1]
When I open falcor.sln and click Generate Solution, the following error appears:

![image](https://github.com/DQLin/VolumetricReSTIRRelease/assets/45633064/e1da6391-eb27-4133-b776-140260993579)

Maybe I'd like some more details on the compilation process

**Comment by Donsome** [comment]
I don't know why I get the download error,  any help will be appreciated
![image](https://github.com/DQLin/VolumetricReSTIRRelease/assets/45633064/b86b3ed7-ce6e-4fa4-bb16-eb30d4943d54)

**Comment by DQLin** [comment]
Check your internet settings😉

**Comment by DQLin** [comment]
Fixed. Check the latest commit.
